{% set name = "litdata" %}
{% set version = "0.2.37" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: 87176cf261bc73f9085e7aa433ab1385b65df2727379d42af2ff9b4854c5ed4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - boto3
    - filelock
    - lightning-utilities
    - numpy
    - python >={{ python_min }}
    - pytorch
    - requests
    - tifffile

test:
  imports:
    - litdata
  commands:
    - pip check
    # https://github.com/Lightning-AI/litdata/pull/230
    - python -c "import numpy as np; from litdata.streaming.serializers import NoHeaderNumpySerializer; serializer = NoHeaderNumpySerializer(); assert serializer.can_serialize(np.ones((10,)))"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Lightning-AI/litdata
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
