{% set name = "litdata" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: e52a035e6c21badd87e4d7cbdd7cb24775f644b8c9ca6662191c01558389b512

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - wheel
  run:
    - lightning-utilities
    - boto3
    - filelock
    - numpy
    - python >=3.8
    - pytorch
    - requests

test:
  imports:
    - litdata
  commands:
    - pip check
    # https://github.com/Lightning-AI/litdata/pull/230
    - python -c "import numpy as np; from litdata.streaming.serializers import NoHeaderNumpySerializer; serializer = NoHeaderNumpySerializer(); assert serializer.can_serialize(np.ones((10,)))"
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litdata
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
