{% set name = "litdata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: 6a2935bbb4c4ec3da670b8b26f5daa59edeee8baabcb89fc2df0c5cfd52d25e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - wheel
  run:
    - filelock
    - lightning-cloud ==0.5.64
    - lightning-utilities >=0.8.0,<0.10.0
    - numpy
    - pillow
    - pyarrow
    - python >=3.8
    - pytorch >=2.1.0
    - torchvision
    - tqdm
    - viztracer

test:
  imports:
    - litdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/lit-data
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
