{% set name = "litdata" %}
{% set version = "0.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: 7efc289b42698583aa581a7112919a571b881ef68b8a8f8c52fa007e62c7b144

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - wheel
  run:
    - boto3
    - filelock
    - numpy
    - python >=3.8
    - pytorch
    - requests

test:
  imports:
    - litdata
  commands:
    - pip check
    # https://github.com/Lightning-AI/litdata/pull/230
    - python -c "import numpy as np; from litdata.streaming.serializers import NoHeaderNumpySerializer; serializer = NoHeaderNumpySerializer(); assert serializer.can_serialize(np.ones((10,)))"
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litdata
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
