{% set name = "litdata" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: a136a450b33b13a3d6fed1302f908185db95c881d2c8fa8bbbbc070c1362bca1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - wheel
  run:
    - boto3
    - filelock
    - lightning-cloud ==0.5.64
    - lightning-utilities <0.11.0,>=0.8.0
    - numpy
    - pillow
    - pyarrow
    - python >=3.8
    - pytorch >=2.1.0
    - torchvision
    - tqdm
    - viztracer

test:
  imports:
    - litdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litdata
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
