{% set name = "litdata" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litdata-{{ version }}.tar.gz
  sha256: 74def833fd916ef3f921b04b3edf03800fe1e837ec864506564f1587519b555c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - wheel
  run:
    - boto3
    - filelock
    - numpy <2.0.0
    - python >=3.8
    - pytorch
    - requests

test:
  imports:
    - litdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/litdata
  summary: The Deep Learning framework to train, deploy, and ship AI products Lightning fast.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
